/*
FILTRANDO AS CONSULTAS DE DADOS (PARTE II)
	Consultas condicionais
*/

SELECT * FROM [TABELA DE PRODUTOS] WHERE
[SABOR] = 'Manga' OR [TAMANHO] = '700 ml'

SELECT * FROM [TABELA DE PRODUTOS] WHERE
[SABOR] = 'Manga' AND [TAMANHO] = '700 ml'

SELECT * FROM [TABELA DE PRODUTOS] WHERE
NOT ([SABOR] = 'Manga' AND [TAMANHO] = '700 ml')

SELECT * FROM [TABELA DE PRODUTOS] WHERE
[SABOR] = 'Manga' AND NOT ( [TAMANHO] = '700 ml')

SELECT * FROM [TABELA DE PRODUTOS] WHERE
[SABOR] IN ('Manga', 'Laranja')

SELECT * FROM [TABELA DE PRODUTOS] WHERE
[SABOR] = 'Manga' OR [SABOR] ='Laranja'

SELECT * FROM [TABELA DE PRODUTOS] WHERE
[SABOR] NOT IN ('Manga', 'Laranja')

/* Aplicação do IN usando condições >, >=, < ou <=
*/
SELECT * FROM [TABELA DE PRODUTOS] WHERE
[SABOR] IN ('Manga', 'Laranja') AND [PREÇO DE LISTA] > 10

SELECT * FROM [TABELA DE PRODUTOS] WHERE
[SABOR] IN ('Manga', 'Laranja') AND [PREÇO DE LISTA] BETWEEN 10 AND 13

SELECT * FROM [TABELA DE PRODUTOS] WHERE
[SABOR] IN ('Manga', 'Laranja') AND [PREÇO DE LISTA] >= 10 AND [PREÇO DE LISTA] <= 13


/*	Usando LIKE
*/

SELECT * FROM [TABELA DE PRODUTOS] WHERE [NOME DO PRODUTO] LIKE '%Litros%'

SELECT * FROM [TABELA DE PRODUTOS] WHERE [NOME DO PRODUTO] LIKE 'Litros%'

SELECT * FROM [TABELA DE PRODUTOS] WHERE [NOME DO PRODUTO] LIKE '%Litros%'
AND [SABOR] = 'Laranja'

