/*
FUNÇÕES AVANÇADAS
	Funções de string
*/

SELECT LTRIM('      OLA')
SELECT RTRIM('OLA      ')
SELECT CONCAT('OLA ','TUDO BEM')
SELECT 'OLA ' + 'TUDO BEM'
SELECT LEFT('RUA AUGUSTA',3)
SELECT RIGHT('RUA AUGUSTA',7)
SELECT UPPER('rua augusta')  
SELECT LOWER('RUA AUGUSTA')  
SELECT REPLACE('R. AUGUSTA','R.','RUA')
SELECT SUBSTRING('RUA AUGUSTA', 1, 3)
SELECT SUBSTRING('RUA AUGUSTA', 2, 4)
SELECT LEN('RUA AUGUSTA')  
SELECT * FROM [TABELA DE CLIENTES]
SELECT CONCAT(NOME, ' (', CPF, ') ') FROM [TABELA DE CLIENTES]


/*	Funções de data
*/

SELECT SYSDATETIME()
SELECT SYSDATETIMEOFFSET()
SELECT SYSUTCDATETIME()
SELECT CURRENT_TIMESTAMP
SELECT GETDATE()
SELECT GETUTCDATE()
SELECT DATENAME(YEAR,GETDATE())
SELECT DATENAME(MICROSECOND,GETDATE())
SELECT DATENAME(MINUTE,GETDATE())
SELECT DATENAME(MONTH,GETDATE())
SELECT DATEPART(MONTH,GETDATE())
SELECT DAY(GETDATE())
SELECT YEAR(GETDATE())
SELECT DATEFROMPARTS(2015,9,1)
SELECT DATENAME(MONTH,DATEFROMPARTS(2015,9,1))
SELECT DATETIME2FROMPARTS(2015,9,1,13,12,11,120,4)
SELECT DATEDIFF(MONTH, DATEFROMPARTS(2015,9,1), GETDATE())
SELECT DATEADD(MONTH, 5, GETDATE())
SELECT ISDATE('2018-01-01')
SELECT ISDATE('2018-25-28')
SELECT * FROM [NOTAS FISCAIS]

SELECT [DATA], CONCAT(DATENAME(DAY, [DATA]), ' ', DATENAME(MONTH, [DATA]), ' ', DATENAME(YEAR, [DATA]))
FROM [NOTAS FISCAIS]


/*	Funções matemáticas
*/

SELECT CEILING(12.333223)
SELECT FLOOR(12.333223)
SELECT RAND()
SELECT ROUND(12.33323323, 2)
SELECT * FROM [ITENS NOTAS FISCAIS]
SELECT [QUANTIDADE], [PREÇO], ROUND(([QUANTIDADE] * [PREÇO]),1) FROM [ITENS NOTAS FISCAIS]


/*	Conversão de dados
*/

SELECT CONVERT(VARCHAR, GETDATE(), 101)
SELECT CONVERT(VARCHAR, GETDATE(), 113)
SELECT CONVERT(VARCHAR, GETDATE(), 130)
SELECT CONVERT(decimal(10,5), 193.57)
SELECT * FROM [TABELA DE PRODUTOS]

SELECT 'O preço do produto ' + [NOME DO PRODUTO] + ' é ' +  [PREÇO DE LISTA]
FROM [TABELA DE PRODUTOS]

SELECT 'O preço do produto ' + [NOME DO PRODUTO] + ' é ' +  CONVERT(VARCHAR, [PREÇO DE LISTA])
FROM [TABELA DE PRODUTOS]

